apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: database
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: mongodb
    repoURL: "https://github.com/srinivasarao2468/stnupai"
    targetRevision: JHC-36
  syncPolicy:
    automated: # Enable automated sync
      prune: true # Prune resources that are no longer defined in Git
      selfHeal: true # Automatically sync if ArgoCD detects any drift from the desired state
    syncOptions:
      - CreateNamespace=True
