apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nodeapp
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: realtime-project
    repoURL: "https://github.com/srinivasarao2468/stnupai/tree/JHC-36/realtime-project"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=False
